services:
  - type: web
    name: spring-boot-todo-app-api
    env: static
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/todoapi-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-21-openjdk/
