services:
  - type: web
    name: spring-boot-app
    env: static
    buildCommand: |
      sudo apt-get update
      sudo apt-get install openjdk-21-jdk -y
      ./mvnw clean install
    startCommand: java -jar target/todoapi-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-21-openjdk/
